export interface CropCategory {
  value: string;
  label: string;
  defaultUnit: string;
  items: string[];
}

export const CROP_CATALOG: CropCategory[] = [
  {
    value: "vegetable",
    label: "Vegetables",
    defaultUnit: "kg",
    items: [
      "Tomato",
      "Potato",
      "Onion",
      "Brinjal (Baingan)",
      "Cauliflower (Phool Gobhi)",
      "Cabbage (Patta Gobhi)",
      "Lady Finger (Bhindi)",
      "Green Chilli",
      "Capsicum (Shimla Mirch)",
      "Bottle Gourd (Lauki)",
      "Bitter Gourd (Karela)",
      "Ridge Gourd (Turai)",
      "Pumpkin (Kaddu)",
      "Cucumber (Kheera)",
      "Carrot (Gajar)",
      "Radish (Mooli)",
      "Beetroot (Chukandar)",
      "Spinach (Palak)",
      "Fenugreek Leaves (Methi)",
      "Coriander Leaves (Dhaniya)",
      "Peas (Matar)",
      "Cluster Beans (Gawar)",
      "French Beans",
      "Sweet Potato (Shakarkandi)",
      "Colocasia (Arbi)",
      "Yam (Jimikand)",
      "Drumstick (Sahjan)",
      "Garlic (Lahsun)",
      "Ginger (Adrak)",
      "Mushroom",
    ],
  },
  {
    value: "fruit",
    label: "Fruits",
    defaultUnit: "kg",
    items: [
      "Mango (Aam)",
      "Banana (Kela)",
      "Apple (Seb)",
      "Guava (Amrood)",
      "Papaya (Papita)",
      "Grapes (Angoor)",
      "Orange (Santra)",
      "Sweet Lime (Mosambi)",
      "Lemon (Nimbu)",
      "Pomegranate (Anar)",
      "Watermelon (Tarbooz)",
      "Muskmelon (Kharbooja)",
      "Pineapple (Ananas)",
      "Litchi",
      "Custard Apple (Sitaphal)",
      "Jackfruit (Kathal)",
      "Sapota (Chikoo)",
      "Ber (Indian Jujube)",
      "Amla (Indian Gooseberry)",
      "Strawberry",
      "Coconut (Nariyal)",
      "Dates (Khajoor)",
    ],
  },
  {
    value: "grain",
    label: "Cereals & Grains",
    defaultUnit: "quintal",
    items: [
      "Wheat (Gehun)",
      "Paddy / Rice (Dhan)",
      "Basmati Rice",
      "Maize (Makka)",
      "Barley (Jau)",
      "Sorghum (Jowar)",
      "Pearl Millet (Bajra)",
      "Finger Millet (Ragi)",
      "Foxtail Millet (Kangni)",
      "Little Millet (Kutki)",
      "Buckwheat (Kuttu)",
      "Amaranth (Ramdana)",
      "Oats (Jai)",
      "Quinoa",
    ],
  },
  {
    value: "pulse",
    label: "Pulses & Oilseeds",
    defaultUnit: "quintal",
    items: [
      "Chickpea (Chana)",
      "Pigeon Pea (Arhar / Tur)",
      "Green Gram (Moong)",
      "Black Gram (Urad)",
      "Lentil (Masoor)",
      "Kidney Bean (Rajma)",
      "Cowpea (Lobia)",
      "Horse Gram (Kulthi)",
      "Field Pea (Matar Dal)",
      "Soybean",
      "Mustard (Sarson)",
      "Groundnut (Moongfali)",
      "Sesame (Til)",
      "Sunflower Seed",
      "Castor (Arandi)",
      "Linseed (Alsi)",
    ],
  },
  {
    value: "spice",
    label: "Spices & Cash Crops",
    defaultUnit: "kg",
    items: [
      "Turmeric (Haldi)",
      "Red Chilli (Sukhi Mirch)",
      "Coriander Seed (Sabut Dhaniya)",
      "Cumin (Jeera)",
      "Fennel (Saunf)",
      "Fenugreek Seed (Methi Dana)",
      "Black Pepper (Kali Mirch)",
      "Cardamom (Elaichi)",
      "Clove (Laung)",
      "Ajwain (Carom Seed)",
      "Sugarcane (Ganna)",
      "Cotton (Kapas)",
      "Jute",
      "Tea Leaf",
      "Coffee Bean",
    ],
  },
  {
    value: "dairy",
    label: "Dairy & Farm Produce",
    defaultUnit: "litre",
    items: [
      "Cow Milk",
      "Buffalo Milk",
      "Curd (Dahi)",
      "Paneer",
      "Ghee",
      "Honey (Shahad)",
      "Farm Eggs",
      "Jaggery (Gud)",
      "Vermicompost",
    ],
  },
];

export const UNITS = ["kg", "quintal", "ton", "dozen", "litre", "piece", "bag"];
